### PR TITLE
updated all dependencies to latest versions

### PR DESCRIPTION
**Pull request by sleidig**
Udated all dependencies to latest versions:

- [x] including Angular 6.1
- [x] keeping TypeScript 2.7 as @angular/compiler-cli doesn't support later versions
- [x] CouchDB authentication is showing `401 (Unauthorized)` in console now ...

### CODE REVIEW

**Comment by sleidig** [comment]
Can anybody look into that pouch-authentication issue?

**Comment by liwde** [comment]
This is really weird. The 401s trigger the sync to fail and in the error handler in pouch-database-manager.service.ts:95, this.alertService is in fact *not* an instance of AlertService, but of AppConfig.

From the Chrome DevTools (`_this` instead of `this` comes from transpilation)

```
> _this
< PouchDatabaseManagerService {_onSyncStatusChanged: EventEmitter, alertService: AppConfig, _localDatabase: PouchDB, _remoteDatabase: PouchDB}

> _this.alertService
< AppConfig {http: HttpClient}
```

**Comment by liwde** [comment]
The dependency on typescript version 2.7.2 is in fact not from the compiler-cli, which would use 2.9.2 (most recent non 3.0 version) as well. The issue however comes from here:

```
npm WARN @ngtools/webpack@6.1.0 requires a peer of typescript@~2.4.0 || ~2.5.0 || ~2.6.0 || ~2.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsickle@0.30.0 requires a peer of typescript@>=2.4.2 <2.9 but none is installed. You must install peer dependencies yourself.
```

**Comment by liwde** [comment]
I found a workaround for the PouchDB issue: https://github.com/NGO-DB/ndb-core/pull/152/commits/44757ba1ea2cf1887c9203df0c299e4c9c61ca1a
We can remove the workaround when the next version of PouchDB (7.0.1) is released; the bug is fixed there.

**Pull request merged**
