### PR TITLE
trying to fix travis config

### LINKED ISSUE #50: Fix Travis CI
currently Travis fails with the error

> ... 'apply' of undefined ...

### PR DESCRIPTION
**Pull request by sleidig**
source https://medium.com/from-the-couch/angular-2-with-travis-ci-922040e01937

(tries to) fix #50

### CODE REVIEW

**Comment by sleidig** [comment]
@fschoell Do we need those `if [[ "$TRAVIS_OS_NAME" == "linux" ]]` parts in the travis config?

**Comment by sleidig** [comment]
aww, I am actually making things worse ... ideas, anyone?

**Comment by fschoell** [comment]
No we don't need that anymore, as long as we keep our testing tied to linux. Could add other os later, but for now that's not necessary in my opinion. 

Fixed the cryptojs error, it's really annoying as those types are outdated and won't match the current cryptojs library. Using require should work, although we won't have typescript support now. However, Travis is now finally working (it's only the test cases that still fail).

@sleidig Do you know why travis is running two jobs on each commit within a pull request?

**Comment by sleidig** [comment]
no idea about those two jobs. Maybe because I removed some config options like branches: only: master?
Anyway, merging this as it gets the job done (thanks to you!): it fixes the basic Travis setup.

Any further tuning for Travis is welcome

**Pull request merged**
