### PR TITLE
created user list view with ng2 smart table

### PR DESCRIPTION
**Pull request by aankitkumar31**
see #63

### CODE REVIEW

**Comment by sleidig** [comment]
@aankitkumar31 please solve the errors from `ng lint`. This will make all the checks for your PR green.

**Comment by aankitkumar31** [comment]
okay

**Comment by Lorsbyjm** [comment]
We decided to use the angular metrial framework, but maybe we can use the code as guide.

**Comment by sleidig** [comment]
not relevant anymore for the current roadmap

**Pull request closed without merging**
