### PR TITLE
Logging msp

### PR DESCRIPTION
**Pull request by mspoeri**
see issue: #60 

### Visible/Frontend Changes
- None

### Architectural/Backend Changes
- [x] Introduced decentralizedlogging service (sentry.io) 
- [x] Adapted Alert module to use new logging service

### CODE REVIEW

**Comment by sleidig** [comment]
Is this "work in progress"? Otherwise, please have a look at the Details of Travis CI below why the checks failed.

**Comment by mspoeri** [comment]
@sleidig 
I´ve overseen some dependencies within the tests.
Now everything should be fixed and tested.

**Comment by sleidig** [comment]
So the Logging is only triggered indirectly through `AlertService` at the moment, right?
What about your remarks that Alerts and Logging are not always the same? Do we have any concrete situations where we should change things? Or any guidelines when to use what in the future?

**Comment by sleidig** [comment]
@mspoeri: If you like, go ahead and merge this PR. It's approved already.

Can you comment a little bit more on the integration:
Is this already integrated and registered with sentry.io? How to access users' logs and monitor this? Uploading will already happen with this (i.e. closing #38)?

**Comment by codingfabi** [comment]
Can this be merged now? Or are we waiting on more commenting?

**Comment by mspoeri** [comment]
@sleidig 

I´ve added a short memo in the README file how to access the logging service. 
Everythis else is still up and running ;)

**Comment by sleidig** [comment]
Thanks!

**Pull request merged**
