### PR TITLE
New Feature: Student Attendance

### PR DESCRIPTION
**Pull request by sleidig**
### Visible/Frontend Changes
- [x] new view `ChildAttendanceComponent` displays list of attendance records
- [x] add/update data through `ChildAttendanceComponent` table
- [x] new template `AttendanceBlockComponent` displays a single attendance record with advance formatting
- [x] ChildrenList shows a column of Attendance records for each child

### Architectural/Backend Changes
- [x] new Entity `AttendanceMonth` representing a monthly attendance dataset of one Child
- [x] new enum `WarningLevel` to represent urgency of action required from a user (socialworker), this should be reused in other modules that analyse the data.
- [x] `ChildrenService` also provides attendance data from the database
- [ ] TODO: EntityMapper handles the references and relationships between `AttendanceMonth` and `Child` Entities efficiently and allows search for all attendance data of a specific student

---
Later features to be considered:
- special view (optimized for mobile) for teacher to call a days attendance of her class directly
- dashboard block to display children for whom follow-up by socialworker is required

### CODE REVIEW

**Comment by sleidig** [comment]
The database interaction to load Attendance records is certainly not efficient yet. Otherwise all basic UI and CRUD functionality is working, however.

Anybody got time for a review?
I'm sure some of the code could still be made more clear and elegant with input from another pair of eyes.

**Comment by codingfabi** [comment]
made a little hotfix to make it work on properly on firefox and added some little other features. otherwise the code looks good.

**Comment by sleidig** [comment]
Thanks @codingfabi ! That are some good changes.

Be careful to check `ng test` and `ng lint` in order to pass the Travis CI checks. Some of your formating was not fitting our standards.

**Comment by sleidig** [comment]
I implemented a reusable `ConfirmationDialogService` to do the delete confirmation consistent with our design in angular material

**Pull request merged**
