### PR TITLE
PR for testing Travis CI

### PR DESCRIPTION
**Pull request by fschoell**

### CODE REVIEW

**Comment by fschoell** [comment]
@sleidig There are 3 entity-mapper test cases that fail on Travis CI while they are running locally without any issues. Do you have an idea what the problem might be here?

**Comment by sleidig** [comment]
Looks like the tests are running now that I fixed a missing async in the tests `beforeEach`.

But now it gets stuck after `build.prod` on
> Error: ENOENT: no such file or directory, open '/home/travis/build/NGO-DB/ndb-core/dist/tmp/app/latest-changes/app/latest-changes/latest-changes.component.html'

@fschoell Any ideas on this one?

**Comment by fschoell** [comment]
@sleidig Fixed the build.prod again, it's the template URL in the component files that has to be within the current directory. But now some other test cases fail, even locally.

**Comment by sleidig** [comment]
great! after fixing a bug due to `undefined !== null` CI is green now :-)

**Pull request merged**
