### PR TITLE
update Angular & dependencies

### PR DESCRIPTION
**Pull request by sleidig**
see issue: #187

### CODE REVIEW

**Comment by sleidig** [comment]
This works for me know. @liwde @RichardNutt can you check and confirm?

**Comment by codingfabi** [comment]
grafik

thats part of my stacktrace right there, so i would not recommend merging. but maybe @liwde or @RichardNutt could run a check of the branch aswell

**Comment by liwde** [comment]
typescript

This is the error-message I'm getting when running `npm i` -- and it already was when we first worked on this. It says, no correct version of typescript is installed, even though it is (manually).

**Comment by liwde** [comment]
I tried it on my second Laptop as well and it worked. Just as a heads up for everyone: If `npm install` does not work as expected, try `npm ci` for fetching all dependencies. This will

a) Clear node_modules before doing anything
b) Just use the `package-lock.json` --> no changed files in git, much faster

I will (squash) merge this now.

**Pull request merged**
