### PR TITLE
Upgraded Dependencies to Angular 2 release version

### LINKED ISSUE #36: Angular2 released
We should upgrade to the final Angular 2 version. No more release candidates =)

### PR DESCRIPTION
**Pull request by fschoell**
This closes #36 

@sebastian-leidig I've already merged your commit with the ng2-bootstrap upgrade (cd6c29f22856429ab350a1a6e1dda7398a4db34b)

`tsc` isn't working because of issues within the ng2-bootstrap library

### CODE REVIEW

**Comment by sebastian-leidig** [comment]
upgrading to typescript 2.0, which is used for `ng2-bootstrap` solves the `tsc` errors.

However, test are still not running ...

**Comment by sleidig** [comment]
I propose we base the project on [angular2-seed](https://github.com/mgechev/angular2-seed/) with which I finally got tests working again ...

**Comment by sleidig** [comment]
@fschoell Could you check and merge if this works for you too?

**Comment by fschoell** [comment]
Angular2-seed looks really nice. `npm serve` and `npm test` are both running and we even get the test coverage. However, building the project doesn't seem to work correctly. `npm run build.dev` works, but the resulting `index.html` tries to include files from the `node_modules` folder which isn't available anymore. `npm run build.prod` is failing because of a missing file (`/dist/tmp/app/alerts/app/alerts/alerts.component.html`in this case).

**Comment by sleidig** [comment]
let's merge this and keep the build issues open in #8 ?

**Comment by fschoell** [comment]
Okay, I'll copy it over to the issue and merge it

**Pull request merged**
